[package]
name = "crucial"
description = "◉ Ordinal wallet and block explorer"
version = "0.0.0"
edition = "2021"
license = "CC0-1.0"
homepage = "https://github.com/raphjaph/crucial"
repository = "https://github.com/raphjaph/crucial"
rust-version = "1.77"

[dependencies]
