[package]
name = "crucial"
description = "Crucial to all"
version = "0.0.1"
edition = "2021"
license = "CC0-1.0"
homepage = "https://github.com/raphjaph/crucial"
repository = "https://github.com/raphjaph/crucial"
rust-version = "1.77"

[dependencies]
